version: '3'
services:
  amqp:
    image: rabbitmq:3-management-alpine
    ports:
      - ${AMQP_PORT}:5672
      - ${AMQP_MANAGEMENT_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${AMQP_USER}
      - RABBITMQ_DEFAULT_PASS=${AMQP_PASSWORD}
  db:
    image: mariadb:10
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
  api:
    build:
      context: .
      dockerfile: etc/api/Dockerfile
    environment:
      FRANKENPHP_CONFIG: "worker ./public/index.php"
      SERVER_NAME: "http://localhost"
    ports:
      - ${API_PORT}:80
    volumes:
      - ./api:/app
    depends_on:
      - db
      - amqp
  app:
    build:
      context: .
      dockerfile: etc/app/Dockerfile
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ./app:/app
    depends_on:
      - api