services:
    ShoppingCart\Query\Product\Infrastructure\Repository\DoctrineProductRepository:
        arguments: [ '@doctrine.orm.default_entity_manager' ]
        public: true

    ShoppingCart\Query\Cart\Infrastructure\Repository\DoctrineCartRepository:
        arguments: [ '@doctrine.orm.default_entity_manager' ]
        public: true

    ShoppingCart\Query\NumberItemsCart\Infrastructure\Repository\DoctrineCartRepository:
        arguments: [ '@doctrine.orm.default_entity_manager' ]
        public: true

    ShoppingCart\Command\Cart\Infrastructure\Repository\DoctrineCartRepository:
        arguments: [ '@doctrine.orm.default_entity_manager' ]
        public: true

    ShoppingCart\Command\Order\Infrastructure\Repository\DoctrineOrderRepository:
        arguments: [ '@doctrine.orm.default_entity_manager' ]
        public: true

    ShoppingCart\Query\Payment\Domain\PaymentSecretRepository: '@ShoppingCart\Query\Payment\Infrastructure\Repository\FakePaymentSecretRepository'